# Generated by Django 3.1.7 on 2021-03-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='elevation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='drone',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
